//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int DonHangID { get; set; }
        public Nullable<int> DiaChiID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public int NguoiDungID { get; set; }
        public decimal TongTien { get; set; }
        public string TinhTrangDonHang { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string TinhTrangThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ThongTinGiaoHang ThongTinGiaoHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
