//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int GioHangID { get; set; }
        public int NguoiDungID { get; set; }
        public int SanPhamID { get; set; }
        public int SoLuong { get; set; }
    
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
